### ISSUE TITLE
Build fail due to dependency

### ISSUE THREAD

**Issue by ghost** [signalfx/lambda-go#3]
Doing a build it's failing, getting this error

`vendor/github.com/signalfx/golib/sfxclient/httpsink.go:284:6: dp.Properties undefined (type *com_signalfx_metrics_protobuf.DataPoint has no field or method Properties)
`

Any recommendation?

**Dep file**
`
[[constraint]]
  name = "github.com/signalfx/lambda-go"
  branch= "master"
`

**Go ENV**
`GOARCH="amd64"
GOBIN="/home/user/go/bin"
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/user/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build486137020=/tmp/go-build -gno-record-gcc-switches"
`

**Go version**
`go version go1.12 linux/amd64`

**Comment by bjsignalfx** [comment]
Issue resolved in release v1.0.0 (https://github.com/signalfx/lambda-go/releases/tag/v1.0.0). Please use this version.
